Fixed format string parsing
SwiftGen/SwiftGenKit pull request #29
Opened 2017-04-30 13:22 UTC by lvsti

The previous pattern would not match for "%%%foobar" (odd number of prefixing %'s) even though it is a valid format string. 

Note that the new pattern has a slightly different behavior: the full match (i.e. `matches.rangeAt(0)`) now spans all preceding %'s of the placeholder, not just one (e.g. "%%%f" instead of just "%f"). As far as I see the full match is not used anywhere in the code, still, let me know if this is a problem and I can iterate on it.

2017-05-07 01:28 UTC, djbe commented
Hi @lvsti,

I think I understand what you're getting at, our parser isn't seeing the `%foobar` in `%%%foobar`, right?

I tried your replacement, but from what I'm seeing, it matches too much? https://regex101.com/r/Vx7Xwo/1 Namely, it matches the following:
- `hello 1%ld` --> `1%ld` instead of `%ld`
- `hello %%%ld` --> `%%%ld` instead of `%ld`

2017-05-07 01:29 UTC, djbe requested changes
Hi @lvsti,

I think I understand what you're getting at, our parser isn't seeing the `%foobar` in `%%%foobar`, right?

I tried your replacement, but from what I'm seeing, it matches too much? https://regex101.com/r/Vx7Xwo/1 Namely, it matches the following:
- `hello 1%ld` --> `1%ld` instead of `%ld`
- `hello %%%ld` --> `%%%ld` instead of `%ld`

2017-05-13 21:49 UTC, lvsti commented
nice catch! I simplified the regex and now it looks good for that particular case as well

2017-05-14 22:17 UTC, djbe requested changes
Hi @lvsti,

Thank you for the updated commit. From some quick testing, the new regex seems to work correctly.

To finish up,  could you please add a changelog entry crediting yourself (and mentioning this PR)? Please use the same format as the other entries (with `.` and 2 spaces at the end of the description).

2017-05-20 23:08 UTC, djbe requested changes

2017-05-20 23:08 UTC, djbe commented on CHANGELOG.md
> +* Improved format string regex to handle escaped "%"s that precede a variable
Please use the same format as the other entries (with . and 2 spaces at the end of the description).

2017-05-21 12:19 UTC, djbe approved these changes

2017-05-21 12:27 UTC, djbe requested changes

2017-05-21 12:27 UTC, djbe commented on Tests/SwiftGenKitTests/StringsTests.swift
> +    XCTAssertEqual(placeholders, [.Float])
Right, so your branch was based on an older version of SwiftGenKit. This needs to be `.float` instead.

2017-05-22 13:21 UTC, merged