Refactor asset catalog code to use our own parsing instead of `actool`.
SwiftGen/SwiftGenKit pull request #43
Opened 2017-05-24 19:51 UTC by djbe

Fixes https://github.com/SwiftGen/SwiftGen/issues/228.
Fixes https://github.com/SwiftGen/SwiftGen/issues/278.
Fixes https://github.com/SwiftGen/SwiftGen/issues/287.

I chose to keep the `Utils/Command.swift` code, we might want it later. Or should I remove it?

2017-05-27 18:19 UTC, AliSoftware requested changes
Except the nested error type, LGTM

2017-05-27 18:19 UTC, AliSoftware commented on Sources/Parsers/AssetsCatalogParser.swift
> +public enum AssetCatalogParserError: Error, CustomStringConvertible {
Prefer a nested type inside `AsstsCatalogParser`

2017-05-27 18:30 UTC, AliSoftware approved these changes

2017-05-27 19:31 UTC, AliSoftware commented
@djbe please ensure that I didn't mess it up during my rebase (it had some conflicts) then you can merge 👍

2017-05-28 11:08 UTC, AliSoftware commented
After thinking about it, yeah maybe we should remove `Utils/Command.swift`.

* We don't use it anymore
* If we do need to use it again maybe it won't be the exact same way, and we can still retrieve it from an old commit if really want to anyway
* Newcomers to the codebase might wonder why we have it if they don't know the history, might be confusing
* We're on the verge of a Breaking version, so it's the best time to remove unneeded stuff, later will be too late
* YAGNI

2017-05-28 20:44 UTC, merged

2017-05-29 00:04 UTC, toshi0383 commented
Awesome!👏

2017-06-28 13:06 UTC, yonaskolb commented
Will this be released in SwiftGen soon? I know a forthcoming 5.0 release is in the works, but if that's a while off, maybe this could be released as a hotfix as it fixes an important bug

2017-06-29 17:11 UTC, AliSoftware commented
As soon as I'm back from my vacation on Monday I'll do everything to fast-track the 5.0 release (which is nearly ready and just need to be pushed but I've close to no data in Rio anyway rn so will have to wait for next week for my data and time once back in Europe)